application: piata-sg
version: 1
runtime: python27
api_version: 1
threadsafe: true

error_handlers:

  - file: error.html

handlers:

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /bootstrap
  static_dir: bootstrap

- url: /
  script: login.app

- url: /profile/?(.*?)/?(.*?)
  script: profile.app
  login: required

- url: /sell/?(.*?)/?(.*?)
  script: sell.app
  login: required

- url: /current
  script: current.app
  login: required

- url: /(login|main)
  script: home.app
  login: required

- url: /.*
  script: error.app

libraries:
- name: jinja2
  version: latest
