application: piata-v1
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /bootstrap
  static_dir: bootstrap

- url: /
  script: login.app

- url: /about_us
  script: login.app

- url: /contact_us
  script: login.app

- url: /profile/?(.*?)
  script: profile.app
  login: required

- url: /sell/?(.*?)
  script: sell.app
  login: required

- url: /.*
  script: home.app
  login: required

libraries:
- name: jinja2
  version: latest
